### ISSUE TITLE
Question about training epoch

### ISSUE THREAD

**Issue by Julesaiyy** [FDUDSDE/WWW2023ConsRec#1]
Thank you very much for your excellent work. How can I get better results by setting epoch to 1000? Is it because the model has already been fitted?

**Comment by WxxShirley** [comment]
Sorry for the late reply.

Actually, we follow previous works AGREE and HCR, which do not split explicit **validation set** for model selection.
If you want to get better results via increasing the training epoch, maybe you can split an extra validation set and obtain the best model when it achieves the best results on the validation set. Hope my answer can help you.

Once again, Thank you for your interests.
